### PR TITLE
Added Hebrew Translation

### PR DESCRIPTION
**Pull request by TickerDev**
Fluent Hebrew Translation to give Israeli players the best experience with it-drugs.
Provided by FiveM Israel with the mission to translate popular FiveM scripts to Hebrew!

### CODE REVIEW

**Comment by AllRoundJonU** [comment]
Hey @TickerDev thanks for the translation I changed the branche to version 1.3.0beta so it is easier to merge the files

**Review by AllRoundJonU — CHANGES_REQUESTED** [review]
Please add the new missing local strings from version 1.3.0beta 

Commit with new locals: https://github.com/it-scripts/it-drugs/commit/b0d846150551aa831a4a36a3b4f221be3ed8b27f

**Comment by TickerDev** [comment]
Just fixed!

**Comment by TickerDev** [comment]
Additional changes in this version:
Currency change from USD to ILS ($ -> ₪)

**Review by AllRoundJonU — CHANGES_REQUESTED** [review]
Please check the new aomit and change the english locales to german in the file

**Comment by TickerDev** [comment]
Changes were now made

**Review by AllRoundJonU — APPROVED** [review]

**Pull request merged**
